const nome = prompt("Nome completo do funcionário")
const dataNascimento = prompt("Data de nascimento do funcionário(ultilize /)")
let endereco = prompt("Qual endereço do funcionário")
const cpf = Number(prompt("Qual cpf do funcionário"))
let escolaridade = prompt("Qual escolaridade do funcionário")
let possuiCNH = prompt("Funcionário possui CNH")
let quantosFilhos = Number(prompt("Quantos filhos possui o funcionário"))
let cargoAtual = prompt("QUal o Cargo atual do funcionario")
let salario = Number(prompt("Qual o salário do funcionario"))
let comissao = prompt("Recebe comissão? Se sim, informe a porcentagem, caso não, responda com zero")
let anoAdmissao = Number(prompt("Informe o ano de admissão"))

console.log(nome)
console.log(dataNascimento)
console.log(endereco)
console.log(cpf)
console.log(escolaridade)
console.log(possuiCNH)
console.log(quantosFilhos)
console.log(cargoAtual)
console.log(salario)
console.log(comissao)
console.log(anoAdmissao)

console.log("O nome do funcionário é " +nome+ ", sua data de nascimento é "+ dataNascimento+ "."  )
console.log("Reside no endereço " + endereco + ". O seu CPF é" + cpf + " .")
console.log("Possui " + escolaridade + " e " + possuiCNH + " possui CNH. ")
console.log("Tem" + quantosFilhos + "filhos. Seu cargo atual é" + cargoAtual)
console.log("Seu salário é " + salario + " e a sua comissão é" + comissao + ". O seu ano de admissão é " + anoAdmissao)
